allowBuilds:
  esbuild: true
  sharp: true

overrides:
  rollup: ">=4.59.0"
  picomatch@<2.3.2: ">=2.3.2"
  picomatch@>=4.0.0 <4.0.4: ">=4.0.4"
  mdast-util-to-hast: ">=13.2.1"
  yaml: ">=2.8.3"
  esbuild: ">=0.28.1"
